### ISSUE TITLE
Curious about the performance comparison in scale x2 and x3

### ISSUE THREAD

**Issue by FizzerYu** [supercaoO/WSR#1]
Hello,
WSR is an impressive work! And I was curious about the performance in scale x2 and x3, could you please provide it.
Thank you very much!

**Comment by supercaoO** [comment]
@FizzerYu Hello, sorry to reply you late.
Following the same evaluation setting as our paper, the unofficial performance of WSR in scale x2 is given as follows,
<table>
	<tr>
	    <th rowspan="2">Methods</th>
	    <th rowspan="2">Scale</th>
	    <th rowspan="2">GPU Time</th>
            <th colspan="5">PSNR/SSIM</th>
	</tr >
	<tr >
	    <th>Set5</td>
	    <th>Set14</td>
	    <th>B100</td>
            <th>Urban100</td>
            <th>Manga109</td>
	</tr>
	<tr>
	    <th>WSR</td>
	    <th>x2</td>
            <th>~1.67s</td>
            <th>37.93/0.9602</td>
            <th>33.52/0.9171</td>
            <th>32.10/0.8985</td>
            <th>31.85/0.9253</td>
            <th>38.32/0.9763</td>
	</tr>
</table>

Since the current WSR only supports scales like x2^n, the performance of WSR in scale x3 is not available.
